{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculaud-fe.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-fe.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # Authentication settings (sensitive)
  {{- if .Values.config.authAuthority }}
  VITE_AUTH_AUTHORITY: {{ .Values.config.authAuthority | quote }}
  {{- end }}
  {{- if .Values.config.authRedirectUri }}
  VITE_AUTH_REDIRECT_URI: {{ .Values.config.authRedirectUri | quote }}
  {{- end }}
  {{- if .Values.config.authLogoutUri }}
  VITE_AUTH_LOGOUT_URI: {{ .Values.config.authLogoutUri | quote }}
  {{- end }}
  
  # Note: Runtime environment variables are handled via RUNTIME_ prefixed environment variables
  # These are injected at container startup by the env.sh script
{{- end }}