apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculaud-fe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-fe.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "calculaud-fe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}