# CI workflow for code quality checks
# Runs linting and build verification on all pushes and pull requests

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        cache: "npm"
    
    - name: Install dependencies
      run: |
        npm ci
    
    - name: Lint with ESLint
      run: |
        npm run lint
    
    - name: Build application
      run: |
        npm run build
    
    - name: Check build output
      run: |
        # Verify build artifacts exist
        ls -la dist/
        echo "Build completed successfully"